apiVersion: v1
kind: ConfigMap
metadata:
  name: call-ai-config
  namespace: call-ai
  labels:
    app.kubernetes.io/name: call-ai
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.call-ai.svc.cluster.local:5672/"
  DATABASE_URL: "mysql+pymysql://call_ai:call_ai_secret@mysql.call-ai.svc.cluster.local:3306/call_ai"
