apiVersion: v1
kind: Service
metadata:
  name: call-ai-app
  namespace: call-ai
  labels:
    app.kubernetes.io/name: call-ai
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: call-ai
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
